---
apiVersion: v1
kind: Pod
metadata:
 name: bert-download-data
 namespace: matrix-benchmarking
spec:
  containers:
  - name: cnt
    image: image-registry.openshift-image-registry.svc:5000/matrix-benchmarking/aiml:bert
    imagePullPolicy: Always
    command: [ "bash", "-ceuxo", "pipefail"]
    env:
    - name: STORAGE
      value: /workspace/bert_tf2/data/download
    args:
    - |
        if [ "$(ls $STORAGE)" ]; then
          echo "Data directory '$STORAGE' not empty, skipping."
          ls "$STORAGE"
          exit 0
        fi
        # workaround until https://github.com/attardi/wikiextractor/issues/283 is solved
        rm -rf /workspace/wikiextractor/
        (cd /workspace; git clone https://github.com/attardi/wikiextractor.git -b v3.0.6)

        # https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow2/LanguageModeling/BERT/data/create_datasets_from_start.sh
        to_download=${1:-"all"}
        pretrained_to_download=${2:-"wiki_only"}

        bash -x data/create_datasets_from_start.sh ${to_download} ${pretrained_to_download}

    volumeMounts:
    - mountPath: /workspace/bert_tf2/data/download
      name: storage-volume
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: benchmarking-bert-dataset
  restartPolicy: Never
