---
apiVersion: v1
kind: Pod
metadata:
 name: bert-download-from-s3
 namespace: matrix-benchmarking
spec:
  containers:
  - name: cnt
    image: registry.access.redhat.com/ubi8/ubi
    command: [ "bash", "-ceuxo", "pipefail"]
    env:
    - name: STORAGE
      value: /workspace/bert_tf2/data/download
    - name: S3_BUCKET_DEST
      value: "s3://psap-coco-mirror/berth-preprocessed/"
    args:
    - |
      dnf install -y --quiet unzip
      curl --silent https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip
      unzip -q awscliv2.zip
      ./aws/install
      mkdir "$HOME/.aws"
      cp /secret/credentials "$HOME/.aws"

      aws s3 cp "$S3_BUCKET_DEST" "$STORAGE" --recursive
    volumeMounts:
    - mountPath: /workspace/bert_tf2/data/download
      name: storage-volume
    - mountPath: /secret/
      name: s3-creds
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: benchmarking-bert-dataset
  - name: s3-creds
    secret:
      secretName: s3-creds
  restartPolicy: Never
