---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmarking-bert-dataset
  namespace: ${namespace}
spec:
  accessModes:
    - ${access_mode}
  resources:
    requests:
      storage: 80Gi
  storageClassName: ${storage_class_name}
