kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-csi-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: "fs-0baeeed6b48dd6377"
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/dynamic_provisioning"
